# Generated by Django 3.2.5 on 2021-08-30 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_disease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='image',
            field=models.FileField(upload_to='images/'),
        ),
    ]
