# Generated by Django 3.2.5 on 2021-08-30 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_disease_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='image',
            field=models.BinaryField(),
        ),
    ]
