# Generated by Django 3.2.5 on 2021-08-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_disease_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
