# Generated by Django 3.2.5 on 2021-08-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_disease_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='user',
            field=models.CharField(default='sandy', max_length=30),
        ),
    ]
