# Generated by Django 3.2.5 on 2021-08-31 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_disease_plant_disease'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='client',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='disease',
            name='fertilizer',
            field=models.CharField(default='', max_length=50),
        ),
    ]
