# Generated by Django 3.2.5 on 2021-09-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20210831_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='plant_disease',
            field=models.CharField(default='', max_length=255),
        ),
    ]
